plugins {
    id 'com.android.application'
}

android {
    namespace 'com.projector.pinlock'
    compileSdk 33

    defaultConfig {
        applicationId "com.projector.pinlock"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
